/* src/graph/Connection.svelte generated by Svelte v3.35.0 */
import { SvelteComponent, init, safe_not_equal } from "../_snowpack/pkg/svelte/internal.js";

import { onMount } from "../_snowpack/pkg/svelte.js";

import {
	width,
	height,
	canvas as canvasStore,
	context as contextStore,
	pixelRatio
} from "../stores.js";

function instance($$self, $$props, $$invalidate) {
	let { item } = $$props;

	const repaint = context => {
		let { from, to } = item;
		context.beginPath();
		context.moveTo(from.x, from.y);
		context.lineTo(to.x, to.y);
		context.stroke();
	};

	const unsubscribe = contextStore.subscribe(value => {
		value && repaint(value);
	});

	$$self.$$set = $$props => {
		if ("item" in $$props) $$invalidate(0, item = $$props.item);
	};

	return [item];
}

class Connection extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, null, safe_not_equal, { item: 0 });
	}
}

export default Connection;